name: CI
on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        python-version: [3.10]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node dependencies
        if: "always()"
        run: |
          if [ -f package.json ]; then npm ci; fi

      - name: Run JS lint & tests
        if: "always()"
        run: |
          if [ -f package.json ]; then npm run lint --if-present; npm test --if-present --silent; fi

      - name: Cache Python pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        if: "always()"
        run: |
          if [ -f requirements.txt ]; then python -m pip install --upgrade pip; pip install -r requirements.txt; fi

      - name: Run Python tests
        if: "always()"
        run: |
          if [ -d tests/py ]; then pytest -q tests/py || exit 1; fi

      - name: Build Docker image (verify build)
        if: "always()"
        run: |
          if [ -f Dockerfile ]; then docker build -t celoht:ci .; fi

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            ./test-results
            ./reports
            ./coverage
            ./*.xml
            ./coverage.xml
