github/workflows/rust.yml

name: CeloHT Rust CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        target: [
          "x86_64-unknown-linux-gnu",
          "aarch64-unknown-linux-gnu",
          "x86_64-pc-windows-msvc",
          "x86_64-apple-darwin",
          "wasm32-unknown-unknown"
        ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.78.2
        profile: minimal
        override: true
        components: rustfmt,clippy,rust-src,rust-analyzer

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-

    - name: Run Rustfmt
      run: cargo fmt --all -- --check

    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Build project
      run: cargo build --release --target ${{ matrix.target }}

    - name: Run tests
      run: cargo test --all --target ${{ matrix.target }}

    - name: WASM bundling (if target is wasm32)
      if: matrix.target == 'wasm32-unknown-unknown'
      run: |
        cargo build --release --target wasm32-unknown-unknown
        wasm-bindgen --out-dir ./wasm/pkg --target web ./target/wasm32-unknown-unknown/release/celoht.wasm
